# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            R for QBio
description:      'Using R for biological analysis'
url:              https://davisqbio.github.io/r_intro
baseurl:          /r_intro
email:            refurrow@ucdavis.edu
feedbackurl:      
author:
  name:           'Rob Furrow'
  url:            

github:
  repo:           https://github.com/davisqbio/r_intro
  #               Be sure the 'Issues' feature is activated in 'Settings'
